name: Update and parse RSS feeds

on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  update-and-parse-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        working-directory: notebooks/rss
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS scraper
        working-directory: notebooks/rss
        run: python rss.py

      - name: Run analysis script
        working-directory: notebooks/rss
        run: python analysis.py

      - name: Copy merged CSV
        run: cp notebooks/rss/output/merged_parsed_documents.csv static/merged_parsed_documents.csv

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add static/merged_parsed_documents.csv notebooks/rss/output/merged_parsed_documents.csv
          git commit -m "Update and parse RSS feeds" || echo "No changes to commit"
          git push

          
